#!/usr/bin/env sh
# 
# Things to take into account: 
# 
#     * if /proc/sys/kernel/unprivileged_userns_clone is 0 you won't be able
#       to do this without root privileges, changing that value fixes it
# 
#     * network is NOT containerized, if you need this, this script is not for
#       you
# 
awk '/^# / { gsub(/# /,""); print }' "$0" >&2
unshare --mount --uts --ipc --pid --fork --user --map-root-user \
	/usr/sbin/chroot "$@"
